# Generated by Django 5.2 on 2025-05-31 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musterapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date']},
        ),
    ]
