# Generated by Django 5.2 on 2025-05-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musterapp', '0002_alter_attendance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('HR', 'HR'), ('Employee', 'Employee')], max_length=100),
        ),
    ]
