# Generated by Django 5.2 on 2025-06-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musterapp', '0003_alter_attendance_options_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='clock_in_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='clock_out_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
