# Generated by Django 5.2.1 on 2025-06-05 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musterapp', '0005_customuser_department_customuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='department',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
    ]
